### ISSUE TITLE
Ability to define properties for which HubSpot would be the master

### ISSUE THREAD

**Issue by Eckin0x** [Atlas-Authority/marketing-automation#64] opened 2021-12-23 16:19 UTC
**Problem:** when updating properties like "First Name" or "Last Name" in HubSpot, the content is overwritten with the MPAC information in the next synchronization.

**Proposed solution:** be able to define a list of properties for which HubSpot will become the master. The sync will populate those fields in case of contact creation, but not in case of contact updates.

**Comment by bberenberg** [comment] 2021-12-23 17:20
My thoughts are that data is currently very dirty, and Atlassian is working to improve the quality, especially around location / address columns. David's approach would allow us to define a list like names, while still consuming address  and other property updates.

@sdegutis what do you think?

**Comment by sdegutis** [comment] 2021-12-23 21:56
@Eckin0x Thanks for the suggestion. 🤔 

So, I'm trying to understand the scenario behind this suggestion, so I know what problem it's specifically attacking. My guesses are that it's either:

1. You're populating HubSpot with MPAC data, but since there are a lot of data inconsistencies (to @bberenberg 's point), you're doing a lot of manual spot-cleanup in HS, or

2. The data MAE is putting in HS is not necessarily problematic, but you just have more context about the data, so you're manually filling in the gaps that MPAC doesn't have.

If it's one of these two cases, I don't think the right solution is to declare ownership on an entire column.

1. In the first scenario, you're eventually going to make HS the owner of all columns as MAE feeds it more and more unsanitized data.

2. In the second, the same will happen except caused by your outer context expanding or touching more columns.

So assuming one of these two scenarios is what we're trying to solve here, I'd suggest:

1. If it's data sanitation at the root:
   a. we work on data sanitation in MAE, and
   b. we add a way to mark *specific fields* on *specific entities* as not updatable by MAE.
      1. This could possibly be done automatically by MAE looking at whether MAE last-updated that field or someone/something else did.

2. If you have an external source of truth about MPAC data that you want fed into HS, maybe we could add it as an input source into MAE? We could add a very simple API for it.

**Comment by bberenberg** [comment] 2021-12-24 03:00
My guess is that David is looking to clean up names and addresses. I don't believe this can be solved within MAE because there isn't a programatic solution.

1.b.i seems like an interesting idea.
2. I think doing enrichment is out of the scope of this ticket.

Ultimately if we can't do your 1.b.i idea, I don't actually see a better model than what David has suggested.

**Comment by Eckin0x** [comment] 2021-12-24 08:08
Hi @sdegutis and @bberenberg, thanks for your answers.

My current need is only to clean first and last names, so that I could send personalized emails to those leads/customers from HubSpot. Because today I have several contacts with "-" instead of the names, and I know their first/last names from their email addresses (firstname.lastname@company.com).

What do you think about defining an optional "HS_OWNER" parameter in your tool configuration?
In this parameter, we would add the property internal name (for instance "hubspot-owner") of a contact property (for instance "HubSpot owns these fields").
This HS field would be a multi-checkbox, listing (some) HubSpot property internal names.

So that when I manually change the first/last names of a contact, I can also update this "HubSpot owns these fields" property, checking "firstname" and "lastname" options.

I'm not a developer, so I hope it's not over-engineered ;-)

**Comment by bberenberg** [comment] 2021-12-24 18:20
I had another thought here. If we go with the 1.b.i approach, it means that once you edit in HS you're forever stuck with the manual data even if the source data is updated. However, this still seems to be the best approach.

**Comment by Eckin0x** [comment] 2022-01-07 09:19
Hi @bberenberg, with my last proposal of having a "HubSpot owns these fields" property for each Company/Contact, you will not be stuck with the manual data. At any time, you can uncheck the fields you want to re-synchronize again.

What do you think about it?
Maybe my proposal was not clear enough, let me know if you would like that I rephrase with more details.

**Comment by bberenberg** [comment] 2022-01-07 16:06
@Eckin0x it seems fine to me, but we need to confirm if the 1.b.i option is possible first. Right now we're focused on other higher priority items like #72 

If your team wants to contribute a PR we're happy to look at that. Otherwise we will prioritize supporting this at some point in the future.

**Comment by sdegutis** [comment] 2022-01-18 19:28
Just looked into it briefly, I don't think HubSpot gives us any metadata on who last updated a given field. But even if it did, we'd have the "stuck forever" problem unless you had a way to opt back into MAE auto-syncing the field. So in any case @Eckin0x your solution is the best, assuming I'm understanding it correctly:

1. We look for a field in HubSpot on each entity type, to dynamically determine which fields we should write to
2. It would be a blacklist of fields that MAE should not write to, so that empty means let MAE update all fields
3. If a field is not in this list for any given contact, and if we have an ENV var for it, MAE updates that field as needed

Also: If HubSpot has a way to set a default value for a given entity type (e.g. Contact), and only override it for a specific contact if that field exists on it, then this could also be a good replacement for HubSpot-field ENV variables altogether. Not sure if that exists though.

**Comment by bberenberg** [comment] 2022-01-18 20:33
@sdegutis did I get this right? 

- Create list of HS Managed Fields
- If field is empty
  - Fill it in
- If field is populated
  - if field is managed, skip
  - if field isn't managed, update the value

**Comment by sdegutis** [comment] 2022-01-18 20:56
Yes, I think.. depending on an ambiguity. I would say:

* Create list of HS Managed Fields (aka MAE Leave Alone fields)
* If field is not in Leave Alone fields:
  * Update its value (fill in or erase, depending on engine run result)
* Else
  * Leave alone

**Comment by bberenberg** [comment] 2022-01-18 21:08
No looks wrong. Take a second look at what I wrote ( I updated to clarify).

**Comment by sdegutis** [comment] 2022-01-18 21:19
Ah, I see. But what if it's empty because the user deleted the value? In that case, MAE should not update it. We can't distinguish that from it not having a value to begin with, in which case MAE _should_ update it. Right?

**Comment by bberenberg** [comment] 2022-01-18 22:32
@Eckin0x are you considering a need to clear a property?

I feel like this isn't needed because if we support this, then how would these fields get populated in the first place? I believe the point here is for manual cleanup, otherwise a property could simply not be mapped in the first place.

**Comment by Eckin0x** [comment] 2022-01-19 01:57
@bberenberg correct, we have no need to clear a property. And what you specified is exactly what we need, thanks!

**Comment by sdegutis** [comment] 2022-01-19 13:32
Not sure what I was thinking, yeah this makes sense and seems like a solid plan 👍

**Comment by sdegutis** [comment] 2022-01-20 15:19
Related to this, it still does seem like a good idea to try to improve our data normalization. Right now, the only things we do for first/last name fields are capitalize them and split them by the first space in the MPAC fullname string. Although I think manual cleaning is inevitable, even a small amount of normalizing code would probably be a big improvement. The main thing we need are transformation rules. The more sample transforms we have (e.g. "john doe [administrator]" should become "John Doe"), the better we can make these rules.

**Comment by bberenberg** [comment] 2022-01-20 17:19
Maybe later, no need within the scope of this issue.

**Comment by bberenberg** [comment] 2022-02-13 21:52
@Eckin0x please take a look at #89 and let us know if you have any feedback.

**Comment by Eckin0x** [comment] 2022-02-17 21:16
@bberenberg tested #89 with firstname, lastname and deal name, it seems to work well - data was not overwritten on the next sync execution.

**Comment by bberenberg** [comment] 2022-02-17 21:22
Merged

**Closed** 2022-02-17 21:21 UTC
Labels: enhancement
