### ISSUE TITLE
Handle upcoming changes

### ISSUE THREAD

**Issue by bberenberg** [Atlas-Authority/marketing-automation#110] opened 2022-06-08 21:25 UTC
Changes are documented at https://atlassianpartners.atlassian.net/wiki/spaces/resources/pages/209977741/Purchasing+System+Updates+for+Marketplace+Partners

Please don't add details to this (public) ticket without ensuring it doesn't violate NDA.

**Comment by boris-moduscreate** [comment] 2022-07-26 23:27
Dupe of #121

**Closed by boris-moduscreate** 2022-07-26 23:27 UTC
